# Generated by Django 5.0.6 on 2024-06-24 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='', verbose_name='Photo fabricant')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PanelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length_in_mm', models.IntegerField()),
                ('width_in_mm', models.IntegerField()),
                ('thickness_in_mm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionOfDecors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.collection')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.decor')),
            ],
            options={
                'unique_together': {('decor', 'collection')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='decors',
            field=models.ManyToManyField(through='panoscan.CollectionOfDecors', to='panoscan.decor'),
        ),
        migrations.AddField(
            model_name='collection',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.market'),
        ),
        migrations.CreateModel(
            name='PanelTypesForDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.decor')),
                ('panel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.paneltype')),
            ],
            options={
                'unique_together': {('decor', 'panel_type')},
            },
        ),
        migrations.AddField(
            model_name='decor',
            name='panel_type',
            field=models.ManyToManyField(through='panoscan.PanelTypesForDecor', to='panoscan.paneltype'),
        ),
        migrations.CreateModel(
            name='PhotoTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.decor')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('date_tested', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paneltype',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.producer'),
        ),
        migrations.AddField(
            model_name='decor',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.producer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.producer'),
        ),
        migrations.CreateModel(
            name='StructuresForDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.decor')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.structure')),
            ],
            options={
                'unique_together': {('decor', 'structure')},
            },
        ),
        migrations.AddField(
            model_name='decor',
            name='structure',
            field=models.ManyToManyField(through='panoscan.StructuresForDecor', to='panoscan.structure'),
        ),
    ]
