# Generated by Django 5.0.6 on 2024-06-26 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decor',
            name='ncs_equivalent',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='producer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='panoscan.producer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paneltype',
            name='thickness_in_mm',
            field=models.FloatField(),
        ),
    ]
