# Generated by Django 5.0.6 on 2024-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0004_alter_decor_ncs_equivalent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='ncs_equivalent',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
