# Generated by Django 5.0.6 on 2024-06-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0006_rename_paneltypesforstructuredecorcombination_finalproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanelType',
            new_name='ProductType',
        ),
        migrations.RenameField(
            model_name='finalproduct',
            old_name='panel_type',
            new_name='product_type',
        ),
        migrations.AlterUniqueTogether(
            name='finalproduct',
            unique_together={('decor_structure_combination', 'product_type')},
        ),
    ]
