# Generated by Django 5.0.6 on 2024-07-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0007_rename_paneltype_producttype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalproduct',
            old_name='decor_structure_combination',
            new_name='decor_structure',
        ),
        migrations.RenameField(
            model_name='structuresfordecor',
            old_name='panel_type',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='structure',
        ),
        migrations.AddField(
            model_name='decorsforcollection',
            name='structures',
            field=models.ManyToManyField(through='panoscan.StructuresForDecor', to='panoscan.structure'),
        ),
        migrations.AlterField(
            model_name='structuresfordecor',
            name='decor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panoscan.decorsforcollection'),
        ),
        migrations.AlterUniqueTogether(
            name='finalproduct',
            unique_together={('decor_structure', 'product_type')},
        ),
    ]
