# Generated by Django 5.0.6 on 2024-07-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0008_rename_decor_structure_combination_finalproduct_decor_structure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalproduct',
            old_name='decor_structure',
            new_name='decor_collection_structure',
        ),
        migrations.RenameField(
            model_name='structuresfordecor',
            old_name='decor',
            new_name='decor_collection',
        ),
        migrations.AlterUniqueTogether(
            name='finalproduct',
            unique_together={('decor_collection_structure', 'product_type')},
        ),
        migrations.AlterUniqueTogether(
            name='structuresfordecor',
            unique_together={('decor_collection', 'structure')},
        ),
    ]
