# Generated by Django 5.0.6 on 2024-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0009_rename_decor_structure_finalproduct_decor_collection_structure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decor',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='collection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='decorsforcollection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='market',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structuresfordecor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
