# Generated by Django 5.0.6 on 2024-07-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0010_rename_is_active_decor_active_collection_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuresfordecor',
            old_name='product_type',
            new_name='product_types',
        ),
    ]
