# Generated by Django 5.0.6 on 2024-07-03 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0011_rename_product_type_structuresfordecor_product_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phototraining',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='decors',
            field=models.ManyToManyField(related_name='collections', through='panoscan.DecorsForCollection', to='panoscan.decor'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='panoscan.market'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='panoscan.producer'),
        ),
        migrations.AlterField(
            model_name='decor',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decors', to='panoscan.producer'),
        ),
        migrations.AlterField(
            model_name='decorsforcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_collections', to='panoscan.collection'),
        ),
        migrations.AlterField(
            model_name='decorsforcollection',
            name='decor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_collections', to='panoscan.decor'),
        ),
        migrations.AlterField(
            model_name='decorsforcollection',
            name='structures',
            field=models.ManyToManyField(related_name='decor_collections', through='panoscan.StructuresForDecor', to='panoscan.structure'),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='decor_collection_structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='final_products', to='panoscan.structuresfordecor'),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_products', to='panoscan.producttype'),
        ),
        migrations.AlterField(
            model_name='phototraining',
            name='decor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_training', to='panoscan.decor'),
        ),
        migrations.AlterField(
            model_name='photouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='panoscan.producer'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='panoscan.producer'),
        ),
        migrations.AlterField(
            model_name='structuresfordecor',
            name='decor_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_collection_structures', to='panoscan.decorsforcollection'),
        ),
        migrations.AlterField(
            model_name='structuresfordecor',
            name='product_types',
            field=models.ManyToManyField(related_name='decor_collection_structures', through='panoscan.FinalProduct', to='panoscan.producttype'),
        ),
        migrations.AlterField(
            model_name='structuresfordecor',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_collection_structures', to='panoscan.structure'),
        ),
    ]
