# Generated by Django 5.0.6 on 2024-07-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0014_formatproduct_alter_photouser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='panoscan.formatproduct'),
        ),
    ]
