# Generated by Django 5.0.6 on 2024-07-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0015_producttype_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='length_in_mm',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='width_in_mm',
        ),
    ]
