# Generated by Django 5.0.6 on 2024-07-18 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0016_remove_producttype_length_in_mm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photouser',
            old_name='date_tested',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='phototraining',
            name='producer',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_training', to='panoscan.producer'),
        ),
        migrations.AddField(
            model_name='phototraining',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
