# Generated by Django 5.0.6 on 2024-08-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0017_rename_date_tested_photouser_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photouser',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
