# Generated by Django 5.0.6 on 2024-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0018_alter_photouser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='image',
            field=models.ImageField(upload_to='photos_producer/None/', verbose_name='Photo fabricant'),
        ),
        migrations.AlterField(
            model_name='phototraining',
            name='photo',
            field=models.ImageField(upload_to='photos_training/'),
        ),
        migrations.AlterField(
            model_name='photouser',
            name='photo',
            field=models.ImageField(upload_to='photos_users/'),
        ),
    ]
