# Generated by Django 5.0.6 on 2024-10-16 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0020_remove_decor_image_remove_phototraining_photo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalproduct',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='format',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='thickness_in_mm',
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_products', to='panoscan.formatproduct'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='thickness_in_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='finalproduct',
            unique_together={('decor_collection_structure', 'product_type', 'format', 'thickness_in_mm')},
        ),
    ]
