# Generated by Django 5.0.6 on 2024-10-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0021_alter_finalproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='photo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='photo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
