# Generated by Django 5.0.6 on 2024-10-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0022_producttype_photo_url_structure_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='noyau',
            field=models.CharField(blank=True, choices=[('brun', 'brun'), ('noir', 'noir'), ('beige', 'beige'), ('blanc', 'blanc'), ('gris clair', 'gris clair')], max_length=15, null=True),
        ),
    ]
