# Generated by Django 5.0.6 on 2024-10-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panoscan', '0023_finalproduct_noyau'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalproduct',
            unique_together={('decor_collection_structure', 'product_type', 'format', 'thickness_in_mm', 'noyau')},
        ),
    ]
